### web
server:
  port: 9222
  servlet:
    context-path: /talent-recruitment
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    min-spare-threads: 10
    maxHttpHeaderSize: 102400
    max-http-form-post-size: -1
  http:
    cors: true
### freemarker
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:./static/,classpath:/static/
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  devtools: #修改后是否重启
    restart:
      enabled: true
  mail:
#    host: ENC(WaLpFXYKnKRNAsG1/p6McGLJrmMYyYN9)
    host: ENC(oRXIQz3ZlJ0tKjBiKuQucBFO824Mfr57)
    username: ENC(KD6MEuH5KoibUBmw8r3xoUQzi/5ajTfntPW8nihla6E=)
    password: ENC(ZClyb+OYGGxdJ9XcKxKXWrzpKmfvdRt/5OoGPTsa7a0=)
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    host: ENC(5cSdetIm44SoAN1rn4ezFUeeODdkfAwa=)
    password: ENC(DQbbWt9QvtuFFkCfuAsLeAbF8qeOB2Wm)
    port: 16379
### mybatis
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

### fastDFS
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 100
    height: 100
  tracker-list: # tracker地址
  - ENC(OmHq7qOml4w83cec2WSZytcgMpwFGwgxMeji3/wSzMc=)